<a href="https://colab.research.google.com/github/tararauzumaki/uits-simulation-and-modelling-lab/blob/main/SIM_Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
np.random.seed(10)
fixed_seed_matrix = np.random.randint(1, 51, (3, 3))
print("Matrix with fixed seed:")
print(fixed_seed_matrix)

# Without fixed seed
random_matrix = np.random.randint(1, 51, (3, 3))
print("\nMatrix without fixed seed:")
print(random_matrix)

Matrix with fixed seed:
[[10 37 16]
 [ 1 50 29]
 [26 30 49]]

Matrix without fixed seed:
[[30 50  9]
 [10  1 43]
 [41 37 17]]


# **Explanation:**
**With fixed seed:**
Using np.random.seed(10) ensures the random number generator produces the same sequence of random numbers every time the code is run. This guarantees that fixed_seed_matrix will always have the same values, providing reproducibility.

**Without fixed seed:**
Without setting a seed, the random number generator produces a different sequence of numbers on each execution. Thus, random_matrix will vary every time you run the code, reflecting true randomness.