<a href="https://colab.research.google.com/github/tararauzumaki/uits-simulation-and-modelling-lab/blob/main/SIM_Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [8]:
# With fixwd seed
np.random.seed(10)
fixed_seed_matrix = np.random.randint(1, 51, (3, 3))
print("Matrix with fixed seed:")
print(fixed_seed_matrix)

Matrix with fixed seed:
[[10 37 16]
 [ 1 50 29]
 [26 30 49]]


In [11]:
# Without fixed seed
random_matrix = np.random.randint(1, 51, (3, 3))
print("Matrix without fixed seed:")
print(random_matrix)

Matrix without fixed seed:
[[50 14  6]
 [14 26 14]
 [29 23 31]]


# **Explanation:**
**With fixed seed:**
Using np.random.seed(10) ensures the random number generator produces the same sequence of random numbers every time the code is run. This guarantees that fixed_seed_matrix will always have the same values, providing reproducibility.

**Without fixed seed:**
Without setting a seed, the random number generator produces a different sequence of numbers on each execution. Thus, random_matrix will vary every time you run the code, reflecting true randomness.